### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by gingermcninja** [stringcode86/SnowGlobeFramework#2]
Any chance you could write up a podspec so people can use cocoapods to install the library?

**Comment by stringcode86** [comment]
I hope to do it in near future, over the weekend at latest.

**Comment by gingermcninja** [comment]
Awesome, thanks!

**Comment by gingermcninja** [comment]
Any updates on this? :)

**Comment by stringcode86** [comment]
Sorry that it took this long, finally got around doing it

**Comment by stringcode86** [comment]
pod "SnowGlobe"
