### ISSUE TITLE
Snow not showing

### ISSUE THREAD

**Issue by MoonheadApps** [stringcode86/SnowGlobeFramework#5]
I have the exact code, but the snow isn't showing. I know it's being created though. I can't hear sounds either, but if I add prints I see the function being called.

**Comment by stringcode86** [comment]
Are you using CocoaPod ? (If so try to copy the files directly into the project)
If you copied files into the project. Could you double check that you included snowflake images ?

I hope this helped solve your problem. Unfortunately I will not have time to debug the code in foreseeable future.
